# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jerico
    username: jerico
    password: leaR4n@0720
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis配置
# 本地sql配置文件xxMapper.xml路径地址
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  # 实体类的包路径
  type-aliases-package: com.jerico.springboot.mybatis.entity
  configuration.map-underscore-to-camel-case: true
  configuration.default-fetch-size: 100
  configuration.default-statement-timeout: 30

# pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

